services:
  postgresdb:
    image: postgres
    container_name: LocalConnection
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-school
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres
  app-backend:
    depends_on:
      - postgresdb
    image: aaaa0000/school-image:1.0.0
    #build : ./
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgresdb:5432/db-school",
        "spring.datasource.username" : "postgres",
        "spring.datasource.password" : "postgres",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db :
